name: Cypress Tests on Linq App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: 

jobs:
  cypress-run:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headed: false
          spec: |
            cypress/e2e/explicitAssertionsOnLinqPhoneNumber.cy.js
            cypress/e2e/implicitAssertionsOnLinqUI.cy.js
            cypress/e2e/checkEmail.cy.js
            cypress/e2e/firstTestPhoneNumber.cy.js
            cypress/e2e/test1VisitWebpage.cy.js
      
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      
      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

